version: "3.9"

include:
  - ./backend/docker-compose.yml
  - ./frontend/docker-compose.yml

services:
  webserver:
    image: nginx:1.21.3-alpine
    container_name: webserver
    restart: always
    ports:
      - "80:80"

    depends_on:
      - api-server
      - frontend-service
    volumes:
      - type: bind
        source: ./nginx/nginx.prod.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    networks:
      - frontend-network
      - api-server-network
